pipeline {
    agent any
    stages {
        stage('Build Application') {
            steps {
                sh 'mvn -f C:\Users\karth\Desktop\Jenkins-Upgradev3\java-tomcat-sample\pom.xml clean package'
            }
            post {
                success {
                    echo "Now Archiving the Artifacts...."
                    archiveArtifacts artifacts: '**/*.war'
                }
            
        }
        
            }
        }
    }
